WeDataSphere/linkis

web/src/apps/linkis/i18n/common/en.json
web/src/apps/linkis/i18n/common/zh.json
web/src/apps/linkis/module/globalHistoryManagement/index.vue
web/src/apps/linkis/module/globalHistoryManagement/viewHistory.vue

(For example: EngineConn-Core defines the the abstractions and interfaces of the EngineConn core functions.
The Engine Service in Linkis 0.x is refactored, EngineConn will handle the engine connection and session management.
Related issues: #590. )
(for example:)
(Please pick either of the following options)  
This change is a trivial rework / code cleanup without any test coverage.  
(or)  
This change is already covered by existing tests, such as (please describe tests).  
(or)  
This change added tests and can be verified as follows:  
(example:)  
- Added tests for submit and execute all kinds of jobs to go through and verify the lifecycles of …

fix: issue 1650 and 1596

---

web/src/apps/URM/module/functionManagement/index.vue
web/src/apps/URM/module/udfManagement/index.vue
web/src/apps/URM/view/urm/index.vue
web/src/apps/linkis/assets/styles/console.scss
web/src/apps/linkis/components/cardList/index.vue
web/src/apps/linkis/i18n/common/en.json
web/src/apps/linkis/i18n/common/zh.json
web/src/apps/linkis/module/ECM/engineConn.vue
web/src/apps/linkis/module/ECM/search.vue
web/src/apps/linkis/module/datasource/index.vue
web/src/apps/linkis/module/globalHistoryManagement/index.vue
web/src/apps/linkis/module/microServiceManagement/index.scss
web/src/apps/linkis/module/microServiceManagement/index.vue
web/src/apps/linkis/module/resourceManagement/index.scss
web/src/apps/linkis/module/resourceManagement/index.vue
web/src/apps/linkis/router.js
web/src/apps/linkis/view/linkis/index.vue
web/src/components/virtualTable/historyTable/historyTable.vue
web/src/dss/view/layout.vue
web/src/dss/view/login/index.vue
web/src/main.js
web/src/utils/watermark.js

fix: issue #2050
- Fix all the problems in issue #2050

fix: issue #2050

---

web/src/apps/linkis/components/tag/index.vue
web/src/apps/linkis/i18n/common/en.json
web/src/apps/linkis/i18n/common/zh.json
web/src/apps/linkis/module/ECM/index.scss
web/src/apps/linkis/module/ECM/index.vue
web/src/apps/linkis/module/ECM/log.vue
web/src/apps/linkis/module/ECM/search.vue
web/src/apps/linkis/module/datasource/index.vue
web/src/apps/linkis/module/globalHistoryManagement/index.scss
web/src/apps/linkis/module/resourceManagement/engineConn.vue
web/src/apps/linkis/module/resourceManagement/index.scss
web/src/apps/linkis/module/resourceManagement/index.vue
web/src/apps/linkis/module/resourceManagement/log.vue
web/src/apps/linkis/module/resourceManagement/search.vue
web/src/apps/linkis/router.js
web/src/apps/linkis/view/linkis/index.vue
web/src/components/consoleComponent/log.vue

Fix：issue 2227

---

linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-core/src/main/scala/org/apache/linkis/gateway/security/GatewaySSOUtils.scala
linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-core/src/main/scala/org/apache/linkis/gateway/security/UserRestful.scala

add function -- clear expired cookie when user login

new function--clear user expired cookie when user login.

---

linkis-dist/package/db/upgrade/1.3.1_schema/mysql/linkis_ddl.sql
linkis-public-enhancements/linkis-datasource/linkis-datasource-manager/server/src/main/java/org/apache/linkis/datasourcemanager/core/dao/DataSourceEnvDao.java
linkis-public-enhancements/linkis-datasource/linkis-datasource-manager/server/src/main/java/org/apache/linkis/datasourcemanager/core/dao/mapper/DataSouceMapper.xml
linkis-public-enhancements/linkis-datasource/linkis-datasource-manager/server/src/main/java/org/apache/linkis/datasourcemanager/core/dao/mapper/DataSourceEnvMapper.xml
linkis-public-enhancements/linkis-datasource/linkis-datasource-manager/server/src/main/java/org/apache/linkis/datasourcemanager/core/restful/DataSourceAdminRestfulApi.java
linkis-public-enhancements/linkis-datasource/linkis-datasource-manager/server/src/main/java/org/apache/linkis/datasourcemanager/core/restful/DataSourceCoreRestfulApi.java
linkis-public-enhancements/linkis-datasource/linkis-datasource-manager/server/src/main/java/org/apache/linkis/datasourcemanager/core/service/DataSourceInfoService.java
linkis-public-enhancements/linkis-datasource/linkis-datasource-manager/server/src/main/java/org/apache/linkis/datasourcemanager/core/service/impl/DataSourceInfoServiceImpl.java
linkis-web/src/common/service/mixin.js
linkis-web/src/dss/module/resourceSimple/engine.vue

Merge dev-1.3.1 into  dev-1.1.6-webank

---

linkis-public-enhancements/linkis-datasource/linkis-metadata-query/server/src/main/java/org/apache/linkis/metadata/query/server/restful/MetadataCoreRestful.java
linkis-public-enhancements/linkis-datasource/linkis-metadata-query/server/src/main/java/org/apache/linkis/metadata/query/server/restful/MetadataQueryRestful.java
linkis-public-enhancements/linkis-datasource/linkis-metadata-query/server/src/test/java/org/apache/linkis/metadata/query/server/restful/MetadataCoreRestfulTest.java
linkis-public-enhancements/linkis-datasource/linkis-metadata-query/server/src/test/java/org/apache/linkis/metadata/query/server/restful/MetadataQueryRestfulTest.java

Add some audit log for datasoure query

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/ECResourceInfoRestfulApi.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EMRestfulApi.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/service/ECResourceInfoService.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/service/impl/ECResourceInfoServiceImpl.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/DefaultEngineStopService.scala
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/dao/NodeManagerMapper.java
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/dao/NodeMetricManagerMapper.java
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/dao/impl/ECResourceRecordMapper.xml
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/dao/impl/NodeMetricManagerMapper.xml
linkis-public-enhancements/linkis-jobhistory/src/test/scala/org/apache/linkis/jobhistory/util/QueryUtilsTest.scala
linkis-public-enhancements/linkis-script-dev/linkis-storage-script-dev-server/src/test/java/org/apache/linkis/filesystem/conf/WorkSpaceConfigurationTest.java
linkis-public-enhancements/linkis-script-dev/linkis-storage-script-dev-server/src/test/java/org/apache/linkis/filesystem/util/WorkspaceUtilTest.java

fix asyn stop ec bug

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/ECResourceInfoRestfulApi.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EngineRestfulApi.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/service/impl/ECResourceInfoServiceImpl.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/DefaultEngineStopService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/EngineStopService.scala
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/dao/impl/ECResourceRecordMapper.xml
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/dao/impl/NodeMetricManagerMapper.xml
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SQLSession.scala

fix spark collect_set result

---

linkis-public-enhancements/linkis-jobhistory/src/main/java/org/apache/linkis/jobhistory/restful/api/QueryRestfulApi.java

fix  jobhistory list  bug

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EngineRestfulApi.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/service/impl/ECResourceInfoServiceImpl.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/util/ECResourceInfoUtils.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/DefaultEngineStopService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/label/service/NodeLabelService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/label/service/impl/DefaultNodeLabelService.scala
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SQLSession.scala

1.1.8 webank fixbug eclist

---

linkis-public-enhancements/linkis-udf/linkis-udf-service/src/main/java/org/apache/linkis/udf/api/UDFRestfulApi.java

Modify the interface isload input parameter attribute in the UDFRestfulApi class to a required parameter
Related pr:#3991
**path**:org.apache.linkis.udf.api.UDFRestfulApi
- [] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).

Input parameter modification

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/excel/StorageExcelWriter.scala
linkis-public-enhancements/linkis-jobhistory/src/main/java/org/apache/linkis/jobhistory/restful/api/QueryRestfulApi.java

Dev 1.3.2 bug fix 

---

linkis-dist/release-docs/LICENSE
pom.xml
tool/dependencies/known-dependencies.txt

**Some jar packages need to be upgraded due to potential security risks**
Related issues: #3942 
Related pr:#3943

Bump protobuf-java from 3.15.8 to 3.16.3

---

linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/i18n/common/zh.json
linkis-web/src/apps/linkis/module/ECM/index.vue
linkis-web/src/apps/linkis/module/ipListManagement/index.vue
linkis-web/src/apps/linkis/module/tenantTagManagement/index.vue
linkis-web/src/apps/linkis/view/linkis/index.vue

1.1.8 web update

---

linkis-public-enhancements/linkis-datasource/linkis-metadata/src/main/java/org/apache/linkis/metadata/restful/api/DataSourceRestfulApi.java
linkis-public-enhancements/linkis-datasource/linkis-metadata/src/main/java/org/apache/linkis/metadata/service/DataSourceService.java
linkis-public-enhancements/linkis-datasource/linkis-metadata/src/main/java/org/apache/linkis/metadata/service/impl/DataSourceServiceImpl.java

add pertition examine api

---

linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-core/src/main/scala/org/apache/linkis/gateway/route/GatewayRouter.scala
linkis-spring-cloud-services/linkis-service-gateway/linkis-spring-cloud-gateway/src/main/java/org/apache/linkis/gateway/springcloud/http/GatewayAuthorizationFilter.java

add route service log in gateway

add gateway log

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/csv/StorageCSVWriter.scala
linkis-public-enhancements/linkis-script-dev/linkis-storage-script-dev-server/src/main/java/org/apache/linkis/filesystem/restful/api/FsRestfulApi.java

result csv export support custom separator

result csv export support custom separator

---

linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/utils/HardwareUtils.scala
linkis-commons/linkis-common/src/test/scala/org/apache/linkis/common/utils/HardwareUtilsTest.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/conf/ECMConfiguration.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/service/impl/DefaultECMHealthService.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/service/impl/DefaultECMRegisterService.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/util/ECMUtils.scala

Ecm infor max memory and core

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/script/ScriptFsWriter.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/script/compaction/CommonScriptCompaction.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/script/parser/CommonScriptParser.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/script/reader/StorageScriptFsReader.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/script/writer/StorageScriptFsWriter.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/source/FileSplit.scala

optimize scriptis code with @set module   distinguish between scriptContent/metadata by annotations

optimize scriptis code with @set module   distinguish between scriptContent/metadata by annotations

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/restful/EntranceRestfulApi.java

[kill job api add user permission check](https://github.com/WeDataSphere/linkis/commit/2d8553a79e45bd4bba870a312f36fae592272458)

kill job api add user permission check

---

linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/service/impl/AbstractEngineConnLaunchService.scala

add ecm link log

---

linkis-public-enhancements/linkis-datasource/linkis-metadata-query/service/hive/src/main/java/org/apache/linkis/metadata/query/service/HiveMetaService.java

fix  hive ds bug

---

linkis-public-enhancements/linkis-jobhistory/src/main/java/org/apache/linkis/jobhistory/restful/api/QueryRestfulApi.java
linkis-public-enhancements/linkis-jobhistory/src/main/scala/org/apache/linkis/jobhistory/conf/JobhistoryConfiguration.scala

The new field of jobhistory returns errorMsgTip

---

linkis-dist/package/db/linkis_ddl.sql

Optimize ddl sql prompt

---

linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/TenantLabelSetUtils.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/UserCreatorIPCheckUtils.scala

Dev 1.3.2 tenant bug fix

---

linkis-public-enhancements/linkis-datasource/linkis-metadata-query/server/src/main/java/org/apache/linkis/metadata/query/server/utils/MetadataUtils.java
linkis-public-enhancements/linkis-datasource/linkis-metadata-query/service/hive/src/main/java/org/apache/linkis/metadata/query/service/HiveMetaService.java

Dev 1.3.2 fix hive ds bug

---

linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/java/org/apache/linkis/ecm/scheduled/EcmClearTask.java
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/java/org/apache/linkis/ecm/scheduled/ScheduledTask.java
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/util/ThreadUtils.java
linkis-dist/package/admin/linkis-ec-clear.sh

Dev 1.3.2 add ecm shell clear

---

linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/conf/Configuration.scala
linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/restful/EntranceRestfulApi.java
linkis-public-enhancements/linkis-script-dev/linkis-storage-script-dev-server/src/main/java/org/apache/linkis/filesystem/restful/api/FsRestfulApi.java

history job user can kill job
add some log
history job user can kill job

Optimize some log  and fix bug

---

linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/utils/Utils.scala
linkis-engineconn-plugins/spark/src/main/resources/python/mix_pyspark.py
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/config/SparkConfiguration.scala
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SparkPythonExecutor.scala

optimize pyspark watch dog

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/csv/StorageCSVWriter.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/source/FileSplit.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/conf/ECMConfiguration.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/util/ECMUtils.scala
linkis-engineconn-plugins/spark/src/main/resources/python/mix_pyspark.py
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SparkPythonExecutor.scala
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/imexport/ExportData.scala

fix some bug after code review

fix some bug after code review

---

linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-core/src/main/scala/org/apache/linkis/gateway/security/UserRestful.scala

gateway-add-baseinfo

---

linkis-web/src/apps/URM/module/udfManagement/addFunctionModal.vue
linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/i18n/common/zh.json
linkis-web/src/apps/linkis/module/EnginePluginManagement/index.vue
linkis-web/src/apps/linkis/module/gatewayAuthToken/index.vue
linkis-web/src/apps/linkis/module/setting/setting.vue
linkis-web/src/apps/linkis/view/linkis/index.vue
linkis-web/src/common/i18n/en.json
linkis-web/src/common/i18n/zh.json
linkis-web/src/common/service/api.js
linkis-web/src/components/consoleComponent/result.vue
linkis-web/src/components/consoleComponent/toolbar.vue
linkis-web/src/dss/view/login/index.vue

merge 1.1.9 webank web

---

linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/util/ECMUtils.scala
linkis-computation-governance/linkis-engineconn/linkis-engineconn-plugin-core/src/main/scala/org/apache/linkis/manager/engineplugin/common/launch/process/JavaProcessEngineConnLaunchBuilder.scala
linkis-computation-governance/linkis-engineconn/linkis-engineconn-plugin-core/src/main/scala/org/apache/linkis/manager/engineplugin/common/resource/GenericEngineResourceFactory.scala
linkis-engineconn-plugins/elasticsearch/src/main/scala/org/apache/linkis/engineplugin/elasticsearch/executor/ElasticSearchEngineConnExecutor.scala
linkis-engineconn-plugins/hive/src/main/scala/org/apache/linkis/engineplugin/hive/executor/HiveEngineConnExecutor.scala
linkis-engineconn-plugins/io_file/src/main/scala/org/apache/linkis/manager/engineplugin/io/executor/IoEngineConnExecutor.scala
linkis-engineconn-plugins/openlookeng/src/main/java/org/apache/linkis/engineplugin/openlookeng/executor/OpenLooKengEngineConnExecutor.java
linkis-engineconn-plugins/pipeline/src/main/scala/org/apache/linkis/manager/engineplugin/pipeline/executor/PipelineEngineConnExecutor.scala
linkis-engineconn-plugins/presto/src/main/scala/org/apache/linkis/engineplugin/presto/executor/PrestoEngineConnExecutor.scala
linkis-engineconn-plugins/python/src/main/scala/org/apache/linkis/manager/engineplugin/python/executor/PythonEngineConnExecutor.scala
linkis-engineconn-plugins/seatunnel/src/main/scala/org/apache/linkis/engineconnplugin/seatunnel/executor/SeatunnelFlinkOnceCodeExecutor.scala
linkis-engineconn-plugins/seatunnel/src/main/scala/org/apache/linkis/engineconnplugin/seatunnel/executor/SeatunnelFlinkSQLOnceCodeExecutor.scala
linkis-engineconn-plugins/seatunnel/src/main/scala/org/apache/linkis/engineconnplugin/seatunnel/executor/SeatunnelSparkOnceCodeExecutor.scala
linkis-engineconn-plugins/shell/src/main/scala/org/apache/linkis/manager/engineplugin/shell/executor/ShellEngineConnConcurrentExecutor.scala
linkis-engineconn-plugins/shell/src/main/scala/org/apache/linkis/manager/engineplugin/shell/executor/ShellEngineConnExecutor.scala
linkis-engineconn-plugins/trino/src/main/scala/org/apache/linkis/engineplugin/trino/executor/TrinoEngineConnExecutor.scala

support JAVA_ENGINE_REQUEST_MEMORY with Unit M

fix inferDefaultMemory loss of precision problem

---

linkis-dist/package/db/linkis_dml.sql
linkis-dist/package/db/upgrade/1.3.2_schema/mysql/linkis_dml.sql

Dev 1.1.9 fix error msg bug

---

linkis-engineconn-plugins/flink/pom.xml
linkis-engineconn-plugins/pipeline/pom.xml
linkis-engineconn-plugins/python/pom.xml
linkis-engineconn-plugins/shell/pom.xml
linkis-engineconn-plugins/spark/pom.xml

exclude resources when build engine tar

---

linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/imexport/CsvRelation.scala

fix export data charset not working

---

linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-server/src/main/scala/org/apache/linkis/ecm/server/service/impl/DefaultEngineConnKillService.java
linkis-computation-governance/linkis-engineconn/linkis-engineconn-plugin-core/src/main/scala/org/apache/linkis/manager/engineplugin/common/launch/process/JavaProcessEngineConnLaunchBuilder.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EMRestfulApi.java
linkis-engineconn-plugins/hive/src/main/resources/log4j2.xml
linkis-engineconn-plugins/shell/src/main/resources/conf/log4j2.xml
linkis-engineconn-plugins/spark/src/main/resources/log4j2.xml
linkis-engineconn-plugins/sqoop/src/main/resources/log4j2.xml

ECM management: adding yarnApp logs and gc logs to engine logs
Related issues: #4385

【1.1.10】Optimize engine log

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/server/DefaultEntranceServer.java
linkis-public-enhancements/linkis-jobhistory/src/main/java/org/apache/linkis/jobhistory/errorcode/JobhistoryErrorCodeSummary.java

【1.1.10】update task cancel msg

---

linkis-public-enhancements/linkis-udf/linkis-udf-service/src/main/java/org/apache/linkis/udf/service/impl/UDFTreeServiceImpl.java

user message missing in log
Related issues:#4389

【1.1.10】Optimize pythonspark log

---

linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/utils/Utils.scala

fix shell upload blocking
Related issues: #4388

【1.1.10】fix shell upload blocking

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/domain/DataType.scala
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SQLSession.scala

Result Set Scramble Problem
Recurrence: select stddev_ samp(col) from values(178357) as tab(col);
"When writing a dolphin file, it becomes garbled. This problem should have existed before."
Related issues: #4390

【1.1.10】Fix the garbled code problem of spark function

---

linkis-computation-governance/linkis-manager/linkis-manager-common/src/main/scala/org/apache/linkis/manager/common/entity/resource/Resource.scala

fix yarn resource add + not correct

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/restful/EntranceRestfulApi.java
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/VarSubstitutionInterceptor.scala

fix the execution code log that was printed lost annotation information.
https://github.com/apache/linkis/issues/4396

fix the execution code log that was printed lost annotation information.

---

linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/launch/SparkSubmitProcessEngineConnLaunchBuilder.scala

https://github.com/apache/linkis/issues/4397

 [Feature] Support scala script deal with custom jar package

---

linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SparkEngineConnExecutor.scala

Spark task log add resource infomation

Spark task log add resource infomation

---

linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/TenantLabelSetUtils.scala
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/TenantConfigrationRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/TenantConfigService.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/impl/TenantConfigServiceImpl.java

Tenant tag support user-*
Related issues:#4391

【1.1.10】Entry tenant label supports common configuration

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/csv/StorageCSVWriter.scala

fix csv export possible missing escape characters

fix csv export possible missing escape characters

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/parser/ParserUtils.java
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/log/HDFSCacheLogWriter.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/utils/CommonLogPathUtils.scala

Adjust  dir check code location

move dir check to HDFSCacheLogWriter.init

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/script/writer/StorageScriptFsWriter.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/source/FileSplit.scala
linkis-commons/linkis-storage/src/test/java/org/apache/linkis/storage/script/writer/StorageScriptFsWriterTest.java
linkis-commons/linkis-storage/src/test/resources/scritpis-test2.sql
pom.xml

Fix custom variable settings

---

docs/errorcode/linkis-engineconn-plugin-core-errorcode.md
linkis-commons/linkis-module/src/main/scala/org/apache/linkis/server/security/SecurityFilter.scala
linkis-computation-governance/linkis-engineconn/linkis-engineconn-plugin-core/src/main/java/org/apache/linkis/manager/engineplugin/errorcode/EngineconnCoreErrorCodeSummary.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/engineplugin/server/conf/EngineConnPluginConfiguration.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/engineplugin/server/localize/AbstractEngineConnBmlResourceGenerator.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/engineplugin/server/service/DefaultEngineConnResourceService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/service/impl/DefaultResourceManager.scala
linkis-web/src/apps/linkis/i18n/common/en.json

engine bml resource compatible prefix v format

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/parser/ParserUtils.java
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/log/HDFSCacheLogWriter.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/utils/CommonLogPathUtils.scala

Reverts WeDataSphere/linkis#100

Revert "move dir check to HDFSCacheLogWriter.init"

---

linkis-computation-governance/linkis-engineconn/linkis-engineconn-executor/accessible-executor/src/main/scala/org/apache/linkis/engineconn/acessible/executor/lock/EngineConnTimedLock.scala

Fix unlock

---

linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/utils/VariableUtils.scala
linkis-computation-governance/linkis-engineconn/linkis-engineconn-plugin-core/src/main/java/org/apache/linkis/manager/engineplugin/errorcode/EngineconnCoreErrorCodeSummary.java
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/EntranceWebSocketService.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/CommentInterceptor.scala
linkis-computation-governance/linkis-entrance/src/test/scala/org/apache/linkis/entrance/interceptor/impl/TestCommentHelper.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/engineplugin/server/localize/AbstractEngineConnBmlResourceGenerator.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/DefaultEngineCreateService.scala
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/persistence/impl/DefaultNodeMetricManagerPersistence.java
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SparkEngineConnExecutor.scala

fix variable identification problem eg -----@set x=y--- Optimize spark log to print repeatedly
- fix NPE bug
- fix variable identification problem eg -----@set x=y---
- Optimize spark log to print repeatedly

Fix NPE bug and variable identification problem

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/errorcode/EntranceErrorCodeSummary.java
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/EntranceServer.scala

optimize about submit empty code after code preprocessing

---

linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/TenantConfigrationRestfulApi.java

fix merge miss code bug

---

linkis-web/src/apps/URM/module/functionManagement/index.vue
linkis-web/src/apps/URM/module/udfManagement/index.vue
linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/i18n/common/zh.json
linkis-web/src/apps/linkis/module/ECM/log.vue
linkis-web/src/apps/linkis/module/datasourceEnv/EditForm/index.vue
linkis-web/src/apps/linkis/module/datasourceEnv/index.vue
linkis-web/src/apps/linkis/module/gatewayAuthToken/index.vue
linkis-web/src/apps/linkis/module/ipListManagement/index.vue
linkis-web/src/apps/linkis/module/resourceManagement/log.vue
linkis-web/src/apps/linkis/module/rmExternalResourceProvider/index.vue
linkis-web/src/apps/linkis/module/setting/setting.vue
linkis-web/src/apps/linkis/module/tenantTagManagement/index.vue
linkis-web/src/apps/linkis/module/udfTree/index.vue
linkis-web/src/apps/linkis/view/linkis/index.vue

bug fix and feature optimization

bug fix and feature optimize

---

linkis-web/package.json
linkis-web/src/apps/linkis/components/variable/index.scss
linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/module/ECM/engineConn.vue
linkis-web/src/apps/linkis/module/ECM/log.vue
linkis-web/src/apps/linkis/module/datasourceAccess/index.vue
linkis-web/src/apps/linkis/module/datasourceEnv/index.vue
linkis-web/src/apps/linkis/module/datasourceType/index.vue
linkis-web/src/apps/linkis/module/datasourceTypeKey/index.vue
linkis-web/src/apps/linkis/module/errorCode/index.vue
linkis-web/src/apps/linkis/module/gatewayAuthToken/index.vue
linkis-web/src/apps/linkis/module/globalHistoryManagement/viewHistory.vue
linkis-web/src/apps/linkis/module/resourceManagement/engineConn.vue
linkis-web/src/apps/linkis/module/resourceManagement/log.vue
linkis-web/src/apps/linkis/module/rmExternalResourceProvider/index.vue
linkis-web/src/apps/linkis/module/tenantTagManagement/index.vue
linkis-web/src/apps/linkis/module/udfManager/index.vue
linkis-web/src/apps/linkis/module/udfTree/index.vue
linkis-web/src/common/i18n/en.json
linkis-web/src/common/i18n/zh.json
linkis-web/src/components/consoleComponent/resultSetList.vue
linkis-web/src/components/consoleComponent/toolbar.vue

fix known web bugs of dev-1.1.10

add 1.1.10 webank web

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/DefaultEngineCreateService.scala

fix：Fix spelling errors in words

---

linkis-dist/package/conf/linkis-mg-gateway.properties

feat：add ldap-userNameFormat example value

feat：add ldap-userNameFormat example value

---

linkis-public-enhancements/linkis-jobhistory/src/main/scala/org/apache/linkis/jobhistory/service/impl/JobHistoryQueryServiceImpl.scala

【1.1.10】fix JobHistory cache bug

---

linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-server-support/src/main/scala/org/apache/linkis/gateway/dss/DSSGatewayConfiguration.scala
linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-server-support/src/main/scala/org/apache/linkis/gateway/dss/DSSGatewayParser.scala
linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-server-support/src/main/scala/org/apache/linkis/gateway/dss/DSSRouteLabelParser.scala

add dss gateway support parser.

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/script/writer/StorageScriptFsWriter.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/source/FileSplit.scala
linkis-commons/linkis-storage/src/test/java/org/apache/linkis/storage/script/writer/StorageScriptFsWriterTest.java
linkis-commons/linkis-storage/src/test/resources/scritpis-test2.sql
linkis-public-enhancements/linkis-jobhistory/src/main/scala/org/apache/linkis/jobhistory/service/impl/JobHistoryQueryServiceImpl.scala
pom.xml

merge dev-1.1.10 to dev-1.1.11

---

linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-authentication/src/main/java/org/apache/linkis/gateway/authentication/errorcode/LinkisGwAuthenticationErrorCodeSummary.java
linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-authentication/src/main/scala/org/apache/linkis/gateway/authentication/service/CachedTokenService.scala

Optimization of token exception scenario description

feat(token)：Optimization of token exception scenario description

---

linkis-commons/linkis-common/src/main/java/org/apache/linkis/common/utils/ByteTimeUtils.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/utils/RMUtils.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/test/scala/org/apache/linkis/manager/rm/utils/RMUtilsTest.scala

Supports the conversion of positive and negative byte numbers to gb

feat(ByteTimeUtils)：Supports the conversion of positive and negative byte numbers to gb

---

linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/restful/ErrorCodeRestfulApi.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/restful/GatewayAuthTokenRestfulApi.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/restful/RmExternalResourceProviderRestfulApi.java

Basic Information Management Delete Interface Add Administrator Authentication

feat(authentication)：Basic Information Management Delete Interface Add Administrator Authentication

---

linkis-engineconn-plugins/sqoop/pom.xml
linkis-engineconn-plugins/sqoop/src/main/java/org/apache/linkis/engineconnplugin/sqoop/client/config/ParamsMapping.java
linkis-engineconn-plugins/sqoop/src/main/resources/log4j2.xml
linkis-engineconn-plugins/sqoop/src/main/scala/org/apache/linkis/engineconnplugin/sqoop/client/RemoteClientHolder.scala
linkis-engineconn-plugins/sqoop/src/main/scala/org/apache/linkis/engineconnplugin/sqoop/exception/DataSourceRpcErrorException.scala
linkis-engineconn-plugins/sqoop/src/main/scala/org/apache/linkis/engineconnplugin/sqoop/executor/SqoopOnceCodeExecutor.scala
linkis-engineconn-plugins/sqoop/src/main/scala/org/apache/linkis/engineconnplugin/sqoop/params/ConnectParamsResolver.scala
linkis-engineconn-plugins/sqoop/src/main/scala/org/apache/linkis/engineconnplugin/sqoop/params/SqoopDataSourceParamsResolver.scala

adjust sqoop ec

---

linkis-commons/linkis-common/src/test/java/org/apache/linkis/common/utils/ByteTimeUtilsTest.java
linkis-computation-governance/linkis-engineconn/linkis-engineconn-executor/accessible-executor/src/main/scala/org/apache/linkis/engineconn/acessible/executor/conf/AccessibleExecutorConfiguration.scala
linkis-computation-governance/linkis-engineconn/linkis-engineconn-executor/accessible-executor/src/main/scala/org/apache/linkis/engineconn/acessible/executor/service/DefaultAccessibleService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/heartbeat/AMHeartbeatService.scala

fix Fixed session issue
1. 去掉idle状态上报
2. 频繁上报状态等待

fix Fixed session issue

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/domain/DataType.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/utils/StorageUtils.scala
linkis-commons/linkis-storage/src/test/scala/org/apache/linkis/storage/domain/DataTypeTest.scala
linkis-commons/linkis-storage/src/test/scala/org/apache/linkis/storage/utils/StorageUtilsTest.scala
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SQLSession.scala

Dev 1.1.11 fix stddev samp bug

---

linkis-commons/linkis-common/src/test/java/org/apache/linkis/common/utils/ByteTimeUtilsTest.java
linkis-dist/package/db/linkis_ddl.sql
linkis-dist/package/db/upgrade/1.4.0_schema/mysql/linkis_ddl.sql
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/conf/UdfTreeConf.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/dao/UdfBaseInfoMapper.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/domain/UdfBaseInfoEntity.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/domain/UdfManagerEntity.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/restful/UdfManagerRestfulApi.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/restful/UdfTreeRestfulApi.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/service/UdfBaseInfoService.java
linkis-public-enhancements/linkis-basedata-manager/src/main/java/org/apache/linkis/basedatamanager/server/service/impl/UdfBaseInfoServicelmpl.java
linkis-public-enhancements/linkis-basedata-manager/src/main/resources/mapper/common/UdfBaseInfoMapper.xml
linkis-public-enhancements/linkis-basedata-manager/src/test/resources/create.sql
linkis-public-enhancements/linkis-basedata-manager/src/test/resources/data.sql
linkis-public-enhancements/linkis-udf/linkis-udf-common/src/main/java/org/apache/linkis/udf/entity/UDFManager.java
linkis-public-enhancements/linkis-udf/linkis-udf-service/src/main/resources/mapper/common/UDFDao.xml
linkis-public-enhancements/linkis-udf/linkis-udf-service/src/main/resources/mapper/common/UDFVersionDao.xml

Optimize UDF function logic：
1. UDF User Management Permission Control
2. UDF classification management permission control and bug handling
Related issues: #

[1.1.11] Optimize UDF function logic

---

linkis-public-enhancements/linkis-configuration/src/main/scala/org/apache/linkis/configuration/service/ConfigurationService.scala

update get configuration logic

update get configuration logic

---

linkis-computation-governance/linkis-engineconn/linkis-computation-engineconn/src/main/scala/org/apache/linkis/engineconn/computation/executor/service/DefaultNodeHeartbeatMsgManager.scala

fix class no found

---

linkis-public-enhancements/linkis-instance-label/linkis-instance-label-server/src/main/resources/mapper/common/InsLabelRelationMapper.xml

Fix:select exclude route label is empty

---

linkis-computation-governance/linkis-engineconn/linkis-computation-engineconn/src/main/scala/org/apache/linkis/engineconn/computation/executor/service/DefaultNodeHeartbeatMsgManager.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/ECResourceInfoRestfulApi.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/service/impl/ECResourceInfoServiceImpl.java

Dev 1.1.11 ec list add unlock time

---

linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/resources/mapper/common/ECResourceRecordMapper.xml

fix eclist api:filter after group by

---

linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-authentication/src/main/java/org/apache/linkis/gateway/authentication/errorcode/LinkisGwAuthenticationErrorCodeSummary.java
linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-authentication/src/main/scala/org/apache/linkis/gateway/authentication/service/CachedTokenService.scala

Optimization of token exception scenario description
Prevent merging of the original exception stack
- extract throwTokenAuthException function

Optimization of token exception scenario description

---

linkis-web/src/apps/linkis/assets/styles/console.scss
linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/i18n/common/zh.json
linkis-web/src/apps/linkis/module/ECM/engineConn.vue
linkis-web/src/apps/linkis/module/ECM/index.vue
linkis-web/src/apps/linkis/module/datasourceAccess/index.vue
linkis-web/src/apps/linkis/module/datasourceEnv/EditForm/index.vue
linkis-web/src/apps/linkis/module/datasourceEnv/index.vue
linkis-web/src/apps/linkis/module/datasourceType/index.vue
linkis-web/src/apps/linkis/module/datasourceTypeKey/index.vue
linkis-web/src/apps/linkis/module/errorCode/index.vue
linkis-web/src/apps/linkis/module/gatewayAuthToken/index.vue
linkis-web/src/apps/linkis/module/globalHistoryManagement/index.vue
linkis-web/src/apps/linkis/module/microServiceManagement/index.vue
linkis-web/src/apps/linkis/module/resourceManagement/engineConn.vue
linkis-web/src/apps/linkis/module/rmExternalResourceProvider/index.vue
linkis-web/src/apps/linkis/module/tenantTagManagement/index.vue
linkis-web/src/apps/linkis/module/udfManager/index.vue
linkis-web/src/apps/linkis/module/udfTree/EditForm/index.vue
linkis-web/src/apps/linkis/module/udfTree/index.scss
linkis-web/src/apps/linkis/module/udfTree/index.vue
linkis-web/src/apps/linkis/module/udfTree/service.js
linkis-web/src/apps/linkis/view/linkis/index.vue

fix web bugs and optimization for web
fix known bugs

fix web bugs and optimization

---

linkis-commons/linkis-storage/src/main/java/org/apache/linkis/storage/exception/StorageErrorCode.java
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/resultset/StorageResultSetReader.scala
linkis-computation-governance/linkis-engineconn/linkis-computation-engineconn/src/main/scala/org/apache/linkis/engineconn/computation/executor/cs/CSResourceParser.scala

1. 修复storage oom 
2. 修复cs 并发问题，加入前缀

Dev 1.1.11 webank fixoom

---

linkis-computation-governance/linkis-jdbc-driver/src/main/scala/org/apache/linkis/ujes/jdbc/LinkisSQLConnection.scala

merge 1.1.11-webank into 1.1.13

Merge  1.1.11 webank into 1.1.13 

---

linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/entity/UserIpVo.java

ITSM bill of lading call, Josn serialization error reported
If JSON contains unknown attributes, they will be ignored and will not cause deserialization to fail.
Related issues: #4618

【1.1.13】add itsm json  fix

---

linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-core/src/main/scala/org/apache/linkis/gateway/security/token/TokenAuthentication.scala
linkis-spring-cloud-services/linkis-service-gateway/linkis-spring-cloud-gateway/src/main/java/org/apache/linkis/gateway/springcloud/http/GatewayAuthorizationFilter.java

print real ip
Related Issues:https://github.com/apache/linkis/issues/4595
Related pr:https://github.com/WeDataSphere/linkis/pull/171

print real ip

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/restful/EntranceRestfulApi.java

Add exception logs when kill job interface
Related pr:https://github.com/WeDataSphere/linkis/compare/dev-1.1.13-webank...WeDataSphere:linkis:dev-1.1.13-webank-add-exception-log

Add exception logs when kill job interface

---

linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/conf/BDPConfiguration.scala
linkis-commons/linkis-common/src/test/java/org/apache/linkis/common/conf/BDPConfigurationTest.java
linkis-commons/linkis-common/src/test/resources/linkis.properties

Related issues: https://github.com/apache/linkis/issues/4284
Related pr: https://github.com/WeDataSphere/linkis/pull/159

properties values support the Chinese

---

linkis-dist/package/db/linkis_dml.sql
linkis-dist/package/db/upgrade/1.4.0_schema/mysql/linkis_dml.sql

fix error code conflict
Related issues:#4617

【1.1.13】fix error code conflict

---

linkis-computation-governance/linkis-engineconn/linkis-computation-engineconn/src/main/scala/org/apache/linkis/engineconn/computation/executor/service/TaskExecutionServiceImpl.scala
linkis-computation-governance/linkis-manager/linkis-manager-common/src/main/scala/org/apache/linkis/manager/common/protocol/resource/ResourceProtocol.scala
linkis-engineconn-plugins/spark/src/main/java/org/apache/linkis/engineplugin/spark/client/context/SparkConfig.java
linkis-engineconn-plugins/spark/src/main/java/org/apache/linkis/engineplugin/spark/client/deployment/YarnApplicationClusterDescriptorAdapter.java
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/SparkEngineConnPlugin.scala

sync  1.4.0   pr  code ,Related pr: https://github.com/apache/linkis/pull/4514/commits/b6d69c88f4c167919e1ec9aebbcaa7785566caba
Related issues:#4615

【1.1.13】sync  1.4.0 code EC onProgressUpdate should to send ResponseTaskRunningInfo

---

linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SparkEngineConnExecutor.scala

fix spark memory count error
Related issues: #4634

【1.1.13】fix spark memory count error

---

linkis-commons/linkis-module/pom.xml
linkis-engineconn-plugins/sqoop/pom.xml
tool/dependencies/known-dependencies.txt

Related issues: https://github.com/apache/linkis/issues/4629
Related pr: https://github.com/WeDataSphere/linkis/pull/160
snakeyaml
当前版本:2.0
引入的模块名:linkis
引入方式：直接
升级注意点:
spring-boot 2.3.12 升级至 2.7.10 否则会存在兼容性问题
spring-security-crypto
当前版本:5.3.9
引入的模块名:linkis-module
引入方式：直接

Security Work Order Upgrade

---

linkis-public-enhancements/linkis-udf/linkis-udf-common/src/main/java/org/apache/linkis/udf/entity/UDFInfo.java
linkis-public-enhancements/linkis-udf/linkis-udf-service/src/main/java/org/apache/linkis/udf/api/UDFRestfulApi.java
linkis-public-enhancements/linkis-udf/linkis-udf-service/src/main/resources/mapper/common/UDFDao.xml
linkis-public-enhancements/linkis-udf/linkis-udf-service/src/test/resources/create.sql

UDF function all interface added description field
Related issues: #4584

【1.1.13】UDF function all interface added description field

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/service/impl/DriverAndYarnReqResourceService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/utils/RMUtils.scala

Optimization of log issues, adding queue names
Related issues: https://github.com/apache/linkis/issues/4642
Related pr: https://github.com/WeDataSphere/linkis/pull/184

Optimization of log issues, adding queue names

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/restful/RMMonitorRest.scala
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/persistence/impl/DefaultNodeManagerPersistence.java
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/resources/mapper/common/NodeManagerMapper.xml

fix queueresources sql bug
issue:#4616

【1.1.13】fix queueresources sql bug

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/utils/FileSystemUtils.scala
linkis-public-enhancements/linkis-script-dev/linkis-storage-script-dev-server/src/main/java/org/apache/linkis/filesystem/restful/api/FsRestfulApi.java

interface fileinfo add totalline

【1.1.13】interface fileinfo add totalline

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/conf/EntranceSpringConfiguration.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/hook/AskEngineConnHook.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/hook/AskEngineConnHookContext.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/DefaultEngineAskEngineService.scala

【1.1.13】remove tenant for entrance

---

linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/ConfigurationRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/util/ConfigurationConfiguration.java

Abnormal scenario：
Configuration for Linkis_ Helper.sh modifying wds.linkis.rm.client.memory.max without adding memory units can also take effect, but a null pointer exception occurred when submitting the job
Related issues: #4633

【1.1.13】Adding specified parameter validation when modifying configuration files

---

linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/conf/BDPConfiguration.scala
linkis-commons/linkis-rpc/src/main/scala/org/apache/linkis/rpc/conf/RPCConfiguration.scala
linkis-dist/package/db/upgrade/1.4.0_schema/mysql/linkis_dml.sql
linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-core/src/main/scala/org/apache/linkis/gateway/parser/GatewayParser.scala

Related issues: https://github.com/apache/linkis/issues/4641

Service support merge ps-data-source-manager ps-metadataquery into ps-datasource 

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/external/yarn/YarnResourceRequester.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/restful/RMMonitorRest.scala
linkis-computation-governance/linkis-manager/linkis-manager-common/src/main/java/org/apache/linkis/manager/common/entity/resource/CommonNodeResource.java
linkis-computation-governance/linkis-manager/linkis-manager-common/src/main/java/org/apache/linkis/manager/common/entity/resource/NodeResource.java

The queue manager page of the front-end page of the Linkis management console needs to include Max Running applications, Num Active Applications, and Num Pending Applications
Related issues: #4700

【1.1.13】queue resources and add parameter maxapps

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/DefaultEngineStopService.scala
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/dao/NodeMetricManagerMapper.java
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/resources/mapper/common/NodeMetricManagerMapper.xml

Before stopping the EC asynchronously, you need to mark the EC as the Shutdown state

---

linkis-computation-governance/linkis-engineconn/linkis-computation-engineconn/src/main/scala/org/apache/linkis/engineconn/computation/executor/bml/BmlEnginePreExecuteHook.scala
linkis-computation-governance/linkis-engineconn/linkis-computation-engineconn/src/main/scala/org/apache/linkis/engineconn/computation/executor/cs/CSResourceParser.scala

Workflow shell node viewing resource file, path usage error
Related issues: #4585

【1.1.13】Workflow shell node viewing resource file, path usage error

---

linkis-computation-governance/linkis-computation-governance-common/src/main/scala/org/apache/linkis/governance/common/paser/CodeParser.scala
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SparkScalaExecutor.scala

Fix scala dont exit issue

---

linkis-computation-governance/linkis-entrance/src/main/java/org/apache/linkis/entrance/restful/EntranceRestfulApi.java

Fallback error message

---

linkis-dist/package/db/linkis_ddl.sql
linkis-dist/package/db/upgrade/1.4.1_schema/mysql/linkis_ddl.sql

fix slow sql add index
Related issues: https://github.com/apache/linkis/issues/4738

【1.1.13】fix slow sql  add index

---

linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/conf/BDPConfiguration.scala
linkis-commons/linkis-module/src/main/scala/org/apache/linkis/server/utils/LinkisMainHelper.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/utils/FileSystemUtils.scala
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/ConfigurationRestfulApi.java
linkis-public-enhancements/linkis-script-dev/linkis-storage-script-dev-server/src/main/java/org/apache/linkis/filesystem/restful/api/FsRestfulApi.java

code revenrt：
1.Version information messages are processed through script
2.The fileinfo interface returns totalline
code review ：
1.The exception of the configuration parameter check is specific to the configuration exception
add  configration exception   catch

code optimize after code review 

---

linkis-commons/linkis-common/src/main/java/org/apache/linkis/common/utils/VariableOperationUtils.java
linkis-commons/linkis-common/src/main/scala/org/apache/linkis/common/utils/VariableUtils.scala
linkis-computation-governance/linkis-computation-governance-common/src/test/scala/org/apache/linkis/governance/common/paser/ScalaCodeParserTest.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/EMRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/ConfigurationRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/impl/TemplateConfigKeyServiceImpl.java
linkis-public-enhancements/linkis-jobhistory/src/main/java/org/apache/linkis/jobhistory/cache/impl/DefaultQueryCacheManager.java
linkis-public-enhancements/linkis-jobhistory/src/main/java/org/apache/linkis/jobhistory/dao/JobHistoryMapper.java
linkis-public-enhancements/linkis-jobhistory/src/main/resources/mapper/common/JobHistoryMapper.xml
linkis-public-enhancements/linkis-jobhistory/src/test/java/org/apache/linkis/jobhistory/dao/JobHistoryMapperTest.java

- 1 VariableOperation for json type
- 2 JobHistoryMapper slow sql optimize
- 3 TemplateConfigKeyServiceImpl apply add transaction for mapper

code optimize after code review

---

linkis-web/src/apps/linkis/components/variable/index.vue
linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/i18n/common/zh.json
linkis-web/src/apps/linkis/module/codeQuery/index.scss
linkis-web/src/apps/linkis/module/codeQuery/index.vue
linkis-web/src/apps/linkis/module/gatewayAuthToken/EditForm/index.vue
linkis-web/src/apps/linkis/module/globalHistoryManagement/index.scss
linkis-web/src/apps/linkis/module/globalHistoryManagement/index.vue
linkis-web/src/apps/linkis/module/globalHistoryManagement/viewHistory.vue
linkis-web/src/apps/linkis/module/resourceManagement/log.vue
linkis-web/src/apps/linkis/module/rmExternalResourceProvider/EditForm/index.vue
linkis-web/src/dss/module/resourceSimple/engine.vue
linkis-web/src/dss/module/resourceSimple/index.scss
linkis-web/src/dss/module/resourceSimple/queue.vue

1. Add engine log viewing entry for viewing historical tasks
2. Code retrieval supports code retrieval by engine type
3. Other optimizations
- Optimizations and new features

Optimization for linkis web and new features

---

linkis-commons/linkis-rpc/pom.xml
pom.xml
tool/dependencies/known-dependencies.txt

upgrade commons-fileupload

---

linkis-web/src/apps/linkis/components/variable/index.vue
linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/i18n/common/zh.json
linkis-web/src/apps/linkis/module/EnginePluginManagement/index.scss
linkis-web/src/apps/linkis/module/EnginePluginManagement/index.vue
linkis-web/src/apps/linkis/module/codeQuery/index.scss
linkis-web/src/apps/linkis/module/codeQuery/index.vue
linkis-web/src/apps/linkis/module/datasource/index.vue
linkis-web/src/apps/linkis/module/datasourceTypeKey/index.vue
linkis-web/src/apps/linkis/module/gatewayAuthToken/EditForm/index.vue
linkis-web/src/apps/linkis/module/globalHistoryManagement/index.scss
linkis-web/src/apps/linkis/module/globalHistoryManagement/index.vue
linkis-web/src/apps/linkis/module/globalHistoryManagement/viewHistory.vue
linkis-web/src/apps/linkis/module/resourceManagement/log.vue
linkis-web/src/apps/linkis/module/rmExternalResourceProvider/EditForm/index.vue
linkis-web/src/dss/module/resourceSimple/engine.vue
linkis-web/src/dss/module/resourceSimple/index.scss
linkis-web/src/dss/module/resourceSimple/queue.vue

Dev 1.1.13 webank web

---

linkis-orchestrator/linkis-computation-orchestrator/src/main/scala/org/apache/linkis/orchestrator/computation/execute/DefaultCodeExecTaskExecutorManager.scala
linkis-orchestrator/linkis-computation-orchestrator/src/main/scala/org/apache/linkis/orchestrator/ecm/ComputationEngineConnManager.scala
linkis-orchestrator/linkis-computation-orchestrator/src/main/scala/org/apache/linkis/orchestrator/ecm/EngineConnManager.scala
linkis-orchestrator/linkis-computation-orchestrator/src/main/scala/org/apache/linkis/orchestrator/ecm/LoadBalanceLabelEngineConnManager.scala
linkis-orchestrator/linkis-computation-orchestrator/src/main/scala/org/apache/linkis/orchestrator/ecm/service/EngineConnExecutor.scala

请求EC时，需要打印linkismanager 实例信息，方便定位请求链路（When requesting EC, it is necessary to print the linkismanager instance information to facilitate locating the requested link）
Related issues: #4840

When requesting EC, print linkismanager instance information

---

linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-core/src/main/scala/org/apache/linkis/ecm/core/launch/ProcessEngineCommandBuilder.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-core/src/main/scala/org/apache/linkis/ecm/core/launch/ProcessEngineConnLaunch.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-core/src/main/scala/org/apache/linkis/ecm/core/utils/PortUtils.scala

EC  start with  app version parameter

---

linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/Explain.scala
linkis-engineconn-plugins/hive/src/main/resources/log4j2.xml
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SQLSession.scala

Spark & Hive Engine Log Ooptimization
Related hive  issues: #4789
Related spark  issues:#4788

Spark & Hive  Engine Log Ooptimization

---

linkis-dist/package/db/module/linkis_configuration.sql
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/dao/ConfigMapper.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/entity/ConfigKey.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/entity/ConfigUserValue.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/ConfigurationRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/ConfigKeyService.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/impl/ConfigKeyServiceImpl.java
linkis-public-enhancements/linkis-configuration/src/main/resources/mapper/common/ConfigMapper.xml
linkis-public-enhancements/linkis-configuration/src/test/resources/create.sql

linkis 管理台新增用户配置&配置管理功能（New user configuration and configuration management functions added to the Linkis management console）
Related User Configuration issues: #4841
Related Configuration Management issues: #4842

【1.1.14】New User Configuration and Configuration Management for Linkis Management Console

---

linkis-public-enhancements/linkis-configuration/src/main/resources/mapper/common/AcrossClusterRuleMapper.xml

fix dev-1.1.14-webank-cross-cluster

fix update rule mapper

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/csv/StorageCSVWriter.scala
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/utils/StorageUtils.scala
linkis-computation-governance/linkis-engineconn-manager/linkis-engineconn-manager-core/src/main/scala/org/apache/linkis/ecm/core/utils/PortUtils.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/service/RequestResourceService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/service/impl/DriverAndYarnReqResourceService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/utils/AcrossClusterRulesJudgeUtils.scala
linkis-engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/executor/SQLSession.scala
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/dao/AcrossClusterRuleMapper.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/entity/AcrossClusterRule.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/AcrossClusterRuleRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/AcrossClusterRuleService.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/impl/AcrossClusterRuleServiceImpl.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/util/CommonUtils.java
linkis-public-enhancements/linkis-instance-label/linkis-instance-label-server/src/main/java/org/apache/linkis/instance/label/restful/InstanceRestful.java

fix line break bug

---

linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/log/CacheLogWriter.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/log/HDFSCacheLogWriter.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/log/LoopArray.scala
linkis-computation-governance/linkis-entrance/src/test/scala/org/apache/linkis/entrance/interceptor/impl/TestHDFSCacheLogWriter.java

fix cache log write bug

---

linkis-web/src/apps/linkis/module/globalHistoryManagement/viewHistory.vue

fix bugs that reading params of undefined when instance doesn't exist

fix instance doesn't exist bug

---

linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/dao/AcrossClusterRuleMapper.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/entity/AcrossClusterRule.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/AcrossClusterRuleRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/AcrossClusterRuleService.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/impl/AcrossClusterRuleServiceImpl.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/util/CommonUtils.java
linkis-public-enhancements/linkis-configuration/src/main/resources/mapper/common/AcrossClusterRuleMapper.xml

Dev 1.1.14 webank jayceyang

---

linkis-commons/linkis-protocol/src/main/java/org/apache/linkis/protocol/constants/TaskConstant.java
linkis-commons/linkis-protocol/src/main/scala/org/apache/linkis/protocol/utils/TaskUtils.scala
linkis-computation-governance/linkis-computation-governance-common/src/main/java/org/apache/linkis/governance/common/protocol/conf/TemplateConfRequest.java
linkis-computation-governance/linkis-computation-governance-common/src/main/java/org/apache/linkis/governance/common/protocol/conf/TemplateConfResponse.java
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/conf/EntranceConfiguration.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/TemplateConfInterceptor.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/interceptor/impl/TemplateConfUtils.scala
linkis-computation-governance/linkis-manager/linkis-label-common/src/main/java/org/apache/linkis/manager/label/constant/LabelKeyConstant.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/dao/TemplateConfigKeyMapper.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/entity/TemplateConfigKeyVO.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/TemplateConfigKeyService.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/impl/TemplateConfigKeyServiceImpl.java
linkis-public-enhancements/linkis-configuration/src/main/resources/mapper/common/TemplateConfigKeyMapper.xml

support ec startup params with templateid

---

linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/impl/TemplateConfigKeyServiceImpl.java
linkis-public-enhancements/linkis-script-dev/linkis-storage-script-dev-server/src/main/java/org/apache/linkis/filesystem/restful/api/FsRestfulApi.java

fix conf template id apply api NPE

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/engine/DefaultEngineCreateService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/service/impl/DriverAndYarnReqResourceService.scala
linkis-orchestrator/linkis-computation-orchestrator/src/main/scala/org/apache/linkis/orchestrator/ecm/ComputationEngineConnManager.scala

remove cross cluster

---

linkis-spring-cloud-services/linkis-service-gateway/linkis-gateway-authentication/src/main/java/org/apache/linkis/gateway/authentication/errorcode/LinkisGwAuthenticationErrorCodeSummary.java

optimize token desc
Related pr: https://github.com/WeDataSphere/linkis/compare/dev-1.1.14-webank...WeDataSphere:linkis:dev-1.1.14-webank-token-desc-optimize?expand=1

optimize token desc

---

linkis-public-enhancements/linkis-error-code/linkis-error-code-client/src/main/java/org/apache/linkis/errorcode/client/handler/LinkisErrorCodeHandler.java

change LinkisErrorCodeHandler to public

change LinkisErrorCodeHandler to public

---

linkis-commons/linkis-rpc/src/main/scala/org/apache/linkis/rpc/conf/RPCConfiguration.scala

1.service merge   ： data-source-manager,  metadataquery,   datasource

datasource service merge

---

linkis-dist/package/db/linkis_dml.sql
linkis-dist/package/db/upgrade/1.4.1_schema/mysql/linkis_dml.sql

Add error code ： 13008 
Related issues: #4886

add  error code  13008

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/restful/ECResourceInfoRestfulApi.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/service/ECResourceInfoService.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/am/service/impl/ECResourceInfoServiceImpl.java
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/java/org/apache/linkis/manager/dao/ECResourceRecordMapper.java
linkis-computation-governance/linkis-manager/linkis-manager-persistence/src/main/resources/mapper/common/ECResourceRecordMapper.xml

New engine status display on the history engine page, new engine status search
Related issues: #4887

【1.1.15】engine  list  add status

---

linkis-dist/package/db/upgrade/1.4.1_schema/mysql/linkis_ddl.sql
linkis-dist/package/db/upgrade/1.4.1_schema/mysql/linkis_dml.sql
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/entity/ConfigKey.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/ConfigurationRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/resources/mapper/common/ConfigMapper.xml

【1.1.15】Is the spark and hive engine configuration restrictions mandatory

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/engineplugin/server/service/DefaultEngineConnResourceService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/heartbeat/AMHeartbeatService.scala
linkis-public-enhancements/linkis-context-service/linkis-cs-server/src/main/java/org/apache/linkis/cs/server/conf/ContextServerConf.java
linkis-public-enhancements/linkis-context-service/linkis-cs-server/src/main/java/org/apache/linkis/cs/server/label/CSInstanceLabelClient.java
linkis-public-enhancements/linkis-context-service/linkis-cs-server/src/test/java/org/apache/linkis/cs/server/conf/ContextServerConfTest.java

fix compile bug

---

linkis-public-enhancements/linkis-ps-common-lock/src/main/java/org/apache/linkis/publicservice/common/lock/CommonLockSpringConfiguration.java

update bean name

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/java/org/apache/linkis/manager/rm/exception/RMErrorCode.java
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/rm/service/impl/DriverAndYarnReqResourceService.scala

add cross cluster rule error

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/engineplugin/server/service/DefaultEngineConnResourceService.scala
linkis-computation-governance/linkis-manager/linkis-application-manager/src/main/scala/org/apache/linkis/manager/am/service/heartbeat/AMHeartbeatService.scala
linkis-dist/package/db/linkis_ddl.sql
linkis-dist/package/db/upgrade/1.4.1_schema/mysql/linkis_ddl.sql
linkis-public-enhancements/linkis-context-service/linkis-cs-server/src/main/java/org/apache/linkis/cs/server/label/CSInstanceLabelClient.java
linkis-public-enhancements/linkis-ps-common-lock/src/main/java/org/apache/linkis/publicservice/common/lock/dao/CommonLockMapper.java
linkis-public-enhancements/linkis-ps-common-lock/src/main/java/org/apache/linkis/publicservice/common/lock/entity/CommonLock.java
linkis-public-enhancements/linkis-ps-common-lock/src/main/java/org/apache/linkis/publicservice/common/lock/service/impl/DefaultCommonLockService.java
linkis-public-enhancements/linkis-ps-common-lock/src/main/resources/mapper/common/CommonLockMapper.xml
linkis-public-enhancements/linkis-ps-common-lock/src/test/java/org/apache/linkis/publicservice/common/lock/dao/CommonLockMapperTest.java
linkis-public-enhancements/linkis-ps-common-lock/src/test/resources/create.sql
linkis-public-enhancements/linkis-ps-common-lock/src/test/resources/data.sql
linkis-public-enhancements/linkis-udf/linkis-udf-service/src/main/java/org/apache/linkis/udf/service/impl/UDFServiceImpl.java

update lock owner field

---

linkis-commons/linkis-rpc/src/main/scala/org/apache/linkis/rpc/conf/RPCConfiguration.scala

service merge ：data-source-manager,metadataquery,datasource

【1.1.15】service merge

---

docs/configuration/linkis-storage.md
linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/conf/LinkisStorageConf.scala

【1.1.15】Storage add file type txt

---

linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/dao/AcrossClusterRuleMapper.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/entity/AcrossClusterRule.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/AcrossClusterRuleRestfulApi.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/AcrossClusterRuleService.java
linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/service/impl/AcrossClusterRuleServiceImpl.java
linkis-public-enhancements/linkis-configuration/src/main/resources/mapper/common/AcrossClusterRuleMapper.xml

fix user to user_name

---

linkis-commons/linkis-storage/src/main/scala/org/apache/linkis/storage/domain/DataType.scala
linkis-commons/linkis-storage/src/test/scala/org/apache/linkis/storage/domain/DataTypeTest.scala

【1.1.15】fix decimal test code

---

linkis-public-enhancements/linkis-jobhistory/src/main/java/org/apache/linkis/jobhistory/restful/api/QueryRestfulApi.java

【1.1.15】job  remove running msg

---

linkis-public-enhancements/linkis-script-dev/linkis-storage-script-dev-server/src/main/java/org/apache/linkis/filesystem/restful/api/FsRestfulApi.java
tool/dependencies/known-dependencies.txt

1.filesystem rename add no admin check

【1.1.15】filesystem rename add no admin check

---

linkis-computation-governance/linkis-manager/linkis-application-manager/src/test/scala/org/apache/linkis/manager/label/conf/LabelManagerConfTest.scala

fix the cluster lable lost problem when ecm restart.

add yarnCluster label

---

linkis-web/src/apps/linkis/components/variable/index.scss
linkis-web/src/apps/linkis/components/variable/index.vue
linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/i18n/common/zh.json
linkis-web/src/apps/linkis/module/ECM/engineConn.vue
linkis-web/src/apps/linkis/module/ECM/index.vue
linkis-web/src/apps/linkis/module/ECM/log.vue
linkis-web/src/apps/linkis/module/acrossClusterRule/index.vue
linkis-web/src/apps/linkis/module/codeQuery/index.vue
linkis-web/src/apps/linkis/module/configManagement/index.vue
linkis-web/src/apps/linkis/module/ipListManagement/index.vue
linkis-web/src/apps/linkis/module/resourceManagement/engineConn.vue
linkis-web/src/apps/linkis/module/resourceManagement/index.vue
linkis-web/src/apps/linkis/module/resourceManagement/search.vue
linkis-web/src/apps/linkis/module/setting/setting.vue
linkis-web/src/apps/linkis/module/tenantTagManagement/index.vue
linkis-web/src/apps/linkis/module/userConfig/index.vue
linkis-web/src/apps/linkis/view/linkis/index.vue
linkis-web/src/components/consoleComponent/resultSetList.vue
linkis-web/src/components/consoleComponent/toolbar.vue

1. across cluster manage page optimization
2. result set download and display optimization
3. resource manage searchbar add status filter

linkis console web optimization and add new features

---

linkis-engineconn-plugins/hive/src/main/resources/log4j2.xml

HIVE engine log optimization
Related issues: #4923

【1.1.16】add hive engine log4j filtering rules

---

linkis-public-enhancements/linkis-jobhistory/src/main/java/org/apache/linkis/jobhistory/restful/api/QueryRestfulApi.java

【1.1.16】interface api opmizition

---

linkis-dist/package/db/linkis_dml.sql
linkis-dist/package/db/upgrade/1.4.1_schema/mysql/linkis_dml.sql

Dev 1.1.16 add error code

---

linkis-commons/linkis-common/src/test/resources/linkis.properties
linkis-commons/linkis-common/src/test/scala/org/apache/linkis/common/conf/ConfigurationTest.scala

add  configration test

---

linkis-commons/linkis-common/src/test/resources/linkis.properties
linkis-commons/linkis-common/src/test/scala/org/apache/linkis/common/conf/ConfigurationTest.scala

【1.1.16】Add unit testing

---

linkis-dist/package/db/linkis_dml.sql
linkis-dist/package/db/upgrade/1.4.1_schema/mysql/linkis_dml.sql

【1.1.16】fix regex bug

---

linkis-engineconn-plugins/hive/src/main/resources/log4j2.xml

【1.1.16】Optimize log matching

---

linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/log/ErrorCodeManager.scala
linkis-computation-governance/linkis-entrance/src/main/scala/org/apache/linkis/entrance/log/LogManager.scala

update error log mark red

---

linkis-engineconn-plugins/hive/src/main/resources/log4j2.xml

 update hive conf

---

linkis-public-enhancements/linkis-configuration/src/main/resources/mapper/common/AcrossClusterRuleMapper.xml

fix linkis_cg_lm_across_cluster_rule to linkis_ps_configuration_across_cluster_rule

fix table name

---

linkis-public-enhancements/linkis-configuration/src/main/java/org/apache/linkis/configuration/restful/api/ConfigurationRestfulApi.java

[1.1.17]fix config bug

---

linkis-web/src/apps/linkis/i18n/common/en.json
linkis-web/src/apps/linkis/i18n/common/zh.json
linkis-web/src/apps/linkis/module/ECM/engineConn.vue
linkis-web/src/apps/linkis/module/ECM/index.vue
linkis-web/src/apps/linkis/module/ECM/log.vue
linkis-web/src/apps/linkis/module/acrossClusterRule/index.vue
linkis-web/src/apps/linkis/module/configManagement/index.vue
linkis-web/src/apps/linkis/module/globalHistoryManagement/viewHistory.vue
linkis-web/src/apps/linkis/module/header/index.vue
linkis-web/src/apps/linkis/module/ipListManagement/index.vue
linkis-web/src/apps/linkis/module/resourceManagement/engineConn.vue
linkis-web/src/apps/linkis/module/resourceManagement/index.vue
linkis-web/src/apps/linkis/module/resourceManagement/log.vue
linkis-web/src/apps/linkis/module/tenantTagManagement/index.vue
linkis-web/src/apps/linkis/module/userConfig/index.vue
linkis-web/src/apps/linkis/view/linkis/index.vue
linkis-web/src/dss/module/footer/index.vue
linkis-web/src/dss/module/header/index.vue
linkis-web/src/dss/module/resourceSimple/job.vue
linkis-web/src/dss/module/resourceSimple/queue.vue

chore: add download log function; optimization for web

---

linkis-engineconn-plugins/flink/src/main/java/org/apache/linkis/engineconnplugin/flink/client/factory/LinkisYarnClusterClientFactory.java
linkis-engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/config/FlinkEnvConfiguration.scala
linkis-engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/factory/FlinkEngineConnFactory.scala
linkis-engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/operator/KillOperator.scala
linkis-engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/operator/clientmanager/FlinkRestClientManager.scala

To support flink with zookeeper high-available policy on
Related issues: 
Related pr:
- 1. FlinkEngineConnFactory - add default ha_mode 'NONE' for manage ec
- 2. KillOperator - optimize kill operator

To support flink with zookeeper high-available policy on

---

linkis-engineconn-plugins/flink/src/main/java/org/apache/linkis/engineconnplugin/flink/client/factory/LinkisYarnClusterClientFactory.java
linkis-engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/config/FlinkEnvConfiguration.scala
linkis-engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/factory/FlinkEngineConnFactory.scala
linkis-engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/operator/KillOperator.scala
linkis-engineconn-plugins/flink/src/main/scala/org/apache/linkis/engineconnplugin/flink/operator/clientmanager/FlinkRestClientManager.scala

1.1.17 flink修改代码合并
